### ISSUE TITLE
Auto configuration form for vc_config

### ISSUE THREAD

**Issue by and1truong** [vietcoop/vc#2]
Support the module provides this file: ./config/module_name.yml

```
foo:
  meta:
    admin: admin/config/foo/bar
    key_1:
      type: file
    key_1:
      type: string
      options:
        o1: v1
        o2: v2
        o3: v3
  key_1: 1
  key_2: %option_value
```

Make sure only user has `vc configuration` permission can access auto forms.
